import type { Metadata } from "next";
import localFont from "next/font/local";

import Footer from "@/layouts/footer/Footer";
import Header from "@/layouts/header/Header";

import "@/assets/styles/globals.scss";

const chakraPetch = localFont({
   src: "../assets/fonts/ChakraPetch-Regular.otf",
   display: "swap",
   variable: "--font-chakra-petch",
   weight: "400",
   style: "normal",
});

const fonts = `${chakraPetch.variable}`;

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={fonts}>
         <body>
            <div className="page-bg">
               <Header />
               {children}
               <Footer />
            </div>
         </body>
      </html>
   );
}
