import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google";
import "@/assets/styles/globals.scss";

const chakraPetch = Chakra_Petch({
   subsets: ["latin"],
   weight: ["300", "400", "500", "600", "700"],
   style: ["normal", "italic"],
   display: "swap",
   variable: "--font-chakra-petch",
});

const fonts = `${chakraPetch.variable}`;

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={fonts}>
         <body>{children}</body>
      </html>
   );
}
